### ISSUE TITLE
Weak filament path 

### ISSUE THREAD

**Issue by Ether-3D** [kieraneglin/Thumper-Blocks#1]
Removed 2 layers of width from the filament path to reduce the chance of rub when installed.

I think this might have made it to thin. Installing the ecas collar would bend the filament path. 
![image1](https://github.com/kieraneglin/Thumper-Blocks/assets/47064043/4cc4cb18-f427-4a90-b475-ad69b388b286)
![image0](https://github.com/kieraneglin/Thumper-Blocks/assets/47064043/193cbe13-6e6e-4425-bd99-e8b5f6ab3b3f)

**Comment by kieraneglin** [comment]
Good callout! This is a known consequence of making the blocks thinner, but I'll look into improving the setup documentation to cover how to best install the ECAS.

The way I do it is build up the full block (except the latch) and push the ECAS in at that point to give it some more rigidity. Another way is to be sure you're gripping near where the ECAS installs when you're pushing so that less pressure is put on those side arms.

I agree it's not ideal but I hope one of those approaches works for you!
